name: Create branch

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: create branch & push
        run: git branch mctest | git push origin mctest
