name: Create branch

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create McBranch
        env:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        run: git remote -v
          | git branch mctest
